### PR TITLE
Remove invalid bold tag in the quickstart document

### PR DESCRIPTION
**Pull request by itchyny**
This bold tag looks like a mistake because it's inside a code block.

### CODE REVIEW

**Comment by ExtReMLapin** [comment]
There is always a guy who want to be in the contributors list while he cannot contribute to the project itself so he make this kind of PR.

**Comment by itchyny** [comment]
I didn't thought of that, I just noticed a typo while I was reading the tutorial. Maybe I should have reported in issue first, thanks.

**Comment by rhysd** [comment]
Only modifying sources is not a contribution. Making documentation better will help people interested in this project.

**Comment by ckennelly** [comment]
@itchyny Thanks for your pull request!  A few of us have been at a conference this week, which has delayed responding to PRs.

I want to be very clear that documentation improvements are welcome and greatly appreciated.  These changes help everyone get started and use TCMalloc.

**Pull request closed without merging**
