### PR TITLE
suppress C++20 deprecated-volatile warning from new LLVM toolchains

### LINKED ISSUE #106: C++20: deprecated compound assignment to volatile variable
tcmalloc fails to build now with latest clang-14 in C++20 mode.

```
external/com_google_tcmalloc/tcmalloc/sampler.h:237:10: error: compound assignment to object of volatile-qualified type 'volatile ssize_t' (aka 'volatile long') is deprecated [-Werror,-Wdeprecated-volatile]
    *ptr += k;
         ^
```

Proposed solution:
```patch
diff --git a/tcmalloc/sampler.h b/tcmalloc/sampler.h
--- a/tcmalloc/sampler.h	(revision ea06ada5e31f4e5c6eb53f66da16d733cec1d7a3)
+++ b/tcmalloc/sampler.h	(date 1637277811947)
@@ -234,7 +234,7 @@
     // sub <reg>, <mem> instruction for subtraction above.
     volatile ssize_t *ptr =
         const_cast<volatile ssize_t *>(&bytes_until_sample_);
-    *ptr += k;
+    *ptr = *ptr + k;
     return false;
   }
   return true;
```

### PR DESCRIPTION
**Pull request by mumbleskates**
Fixes #106

### CODE REVIEW

**Review by ckennelly — APPROVED** [review]

**Comment by mumbleskates** [comment]
Bump, copybara please

**Comment by mumbleskates** [comment]
@ckennelly Does the bot need a kick to make it do the merge? It seems like it's stuck again, I think this has happened to me before

**Comment by ckennelly** [comment]
When run through our presubmit checks, it looks like this can trigger `-Werror=unknown-pragmas` if the version of Clang building it doesn't understand the pragma.

I'm not sure if it's worth updating `copts.bzl` accordingly, or if there's a more elegant workaround.

**Comment by mumbleskates** [comment]
Fair enough; I've moved it to `copts.bzl` since we probably already have a pretty close eye on anything being done with `volatile` at this point.

**Pull request merged**
